### ISSUE TITLE
TypeError in line 27

### ISSUE THREAD

**Issue by josn0w** [Elijas/auto-youtube-subscription-playlist-2#1]
TypeError: Second argument to Function.prototype.apply must be an array. (line 27, file "")

**Comment by Elijas** [comment]
Went through the instructions from scratch, inserted "ALL" keyword, could not reproduce the bug (everything worked fine).

Could you provide more details?

**Comment by theit8514** [comment]
I encountered this too. Removing the try/catch around the function results in:
```Access Not Configured. The API (YouTube Data API) is not enabled for your project. Please use the Google Developers Console to update your configuration. (line 133, file "Code")```

I resolved it by going to Resources > Developers Console Project > Click the link to your API console project > On the left, APIs & Auth > APIs > YouTube Data API > Enable API.

When I first brought up the API from Advanced Google services, I think it brought up a previous API instead of the one attached to the sheet. Doing it via this method brings up that project's API console.
