### ISSUE TITLE
Videos being repeatedly added to playlist

### ISSUE THREAD

**Issue by sk33ny** [Elijas/auto-youtube-subscription-playlist-2#115]
This just started yesterday, the same 5 videos get added over and over to my playlist every time the script runs.

I'm getting the following error:
`Couldn't update playlist with video (htJUqjVU5nc), ERROR: Message: [API call to youtube.playlistItems.insert failed with error: Precondition check failed.] Details: {"message":"Precondition check failed.","code":400,"errors":[{"reason":"failedPrecondition","message":"Precondition check failed.","domain":"global"}]}`

**Comment by victorjzsun** [comment]
Apparently the video is private but instead of getting a 404, we get a different error. I've changed the script to catch similar errors by trying to find the offending video regardless of response code, so should be fixed now. [Please update your script](https://github.com/Elijas/auto-youtube-subscription-playlist-2#update-script) and let me know if the issue persists.

**Comment by sk33ny** [comment]
I updated the script and everything is working again. Thank you for the quick fix!

**Comment by victorjzsun** [comment]
Closing this now as it's been fixed
