### ISSUE TITLE
Update in batches (x days)

### ISSUE THREAD

**Issue by davisjk** [Elijas/auto-youtube-subscription-playlist-2#128]
This script is great, but I have a lot of catching up to do on my music subscriptions. So much so that I can't do it all at once because I pass my quota limit mid update. Rather than having to manually update the last update timestamp to do it gradually, I think it would be very convenient to let it automatically catch up in batches of x days.

I implemented this feature in a new pull request https://github.com/Elijas/auto-youtube-subscription-playlist-2/pull/127

View my updated spreadsheet copy here https://docs.google.com/spreadsheets/d/1PjrNcyTr03GPb0t5y0g9ZUsZrJIuFAJ0onB_P_AQMYc/edit?usp=sharing

**Comment by Fabian42** [comment]
I sometimes do that, too. But would a better solution not be to just stop and update the timestamp as soon as a quota error occurs (or maybe anticipate it) instead of forcing the user to guess how many days are equivalent to how many abstract quota points? And even then, it could still run into limits for some days, while not even getting close to the limit on other days. See also #62.

**Comment by davisjk** [comment]
That's a very good point and much more user friendly. I'll try to implement that instead.

**Comment by davisjk** [comment]
I'm gonna close this as a duplicate.
