### ISSUE TITLE
im not getting any video in my playlist

### ISSUE THREAD

**Issue by 9acca9** [Elijas/auto-youtube-subscription-playlist-2#133]
Probably im doing something wrong.

i understand that i have to put in the left (in playlistid) MY playlistid, the one where i want all the videos from other channels.
and in Channel Ids put ALL or... the channel id of the channel i want to get the files. 
Ok

if i put ALL i see in debug that i get 147 videos:
![imagen](https://github.com/Elijas/auto-youtube-subscription-playlist-2/assets/25393371/6b806aae-b8aa-4cd7-822b-6d5f69bb36d5)

But... when i go to see my playlist, the one i put the id to "save" the videos i dont see nothing. There is no videos (well, just one video that i add by hand).
And if instead of put ALL i put the channel id of the channel i want to get the videos:  UCJlYsz0wNkoaOhPKVnscKXQ i dont get nothing. No error in DEBUG just:
![imagen](https://github.com/Elijas/auto-youtube-subscription-playlist-2/assets/25393371/d0438985-f32d-4e86-9d7f-e5adc7e62218)

And i want to get all (im talking about all, from the starting point of the channel) the videos from that channel (is the channel of a pianist that i like to hear) 

So... what im doing wrong?
Thanks.

**Comment by victorjzsun** [comment]
The first attempt failed because the script was unable to find the channels with the given ids. I'm assuming you're subscribed to channels that don't actually exist, and that's causing the script to fail. As a side note, the debug data should also include the final conclusions (succeeded or failed). A fix will be made for these two asap. I wonder if you can find out which channels those are and somehow unsubscribe to them?

The second attempt succeeded, but no videos were published by the channel in the time specified. The script does not gather videos from the starting point of the channel, only the ones published since the timestamp in column B (if there's no timestamp there, then from one day in the past). If you want to get more videos, you'll need to set a very early timestamp. However, be careful as you might hit your quota very fast if you're adding a lot of videos

**Comment by 9acca9** [comment]
thank you very much!
well, i dont read the timestamp part.
Im interested in get all the videos from that channel in a playlist in youtube, and if in the future i want to take some other videos i will put them in another playlist.

And about you warn me... yes:
![imagen](https://github.com/Elijas/auto-youtube-subscription-playlist-2/assets/25393371/025d4675-ce4a-471e-9fe4-23407ce03a45)

it seems that not even try.
But, read all the videos! I will change to less time but... for getting all the videos, it will be possible to add a starting date and end date? so i can feed the playlist in 200 videos at a time? or maybe there is other way, i just think that.
Thanks!

**Comment by victorjzsun** [comment]
Soon, we'll be able to do it 200 videos at a time, once @davisjk finishes his PR. As of this moment, we can't add lots of videos mainly due to the high quota cost.

**Comment by victorjzsun** [comment]
For adding videos between two dates, you can follow #129

**Comment by victorjzsun** [comment]
Let me know if that answers your question, and if so, feel free to close this issue

**Comment by 9acca9** [comment]
oh, i just see your response. I will then wait for that enhancement.
Thanks!
