### ISSUE TITLE
Shorts can now be 3 minutes long

### ISSUE THREAD

**Issue by Fabian42** [Elijas/auto-youtube-subscription-playlist-2#137]
The filter needs to be updated.

**Comment by Fabian42** [comment]
I have never properly learned JavaScript and only edited this directly on GitHub, but I think my code should work. I also modified a part that was hard to understand for me and replaced it with a regex, which might be hard to understand for people who have little regex knowledge. 🤔 Meh, I still think it is better than before and the old logic would have not worked nearly as well for the new condition.
I will now make that change in my own copy as well. I will report back if I notice Shorts still coming through or errors or so.

**Comment by Fabian42** [comment]
I set the timestamp of my Shorts exclusion row back by a couple hours, put a channel there that sometimes uploads legitimate videos <3min and it did not get added again. So it seems to work, with the expected false positives.

**Comment by BennyAckermann** [comment]
Did you possibly forget to update the Google Sheets template (column E is still called "Shorts? (No)") as well as mentioning in the readme how to actually use the changed function?

Am I now supposed to put a number or digit into column E instead of the words yes or no and if so, in which format (seconds, minutes, ...) or are the words yes and no still work the same, just with three minutes instead of one as a new fixed value co compare with?

**Comment by Fabian42** [comment]
It is still the same, just excludes <3min now. And the readme mentions that.
