### ISSUE TITLE
Script is not working.

### ISSUE THREAD

**Issue by Elijas** [Elijas/auto-youtube-subscription-playlist-2#39]
Since 2019-09-18 the script has stopped working,

If you're a user:
- Please describe the bug in more detail
- Feel free to [crowdfund the fix](https://issuehunt.io/r/Elijas/auto-youtube-subscription-playlist-2/issues/39)

If you're a programmer:
- We'd appreciate if you could take a look at it, I'd happily merge the PR and give a shout-out in the main README.

**Comment by dudemario** [comment]
What do you mean by the script has stopped working? I was able to use it just now. You will have to change the playlists given as sample since those playlists do not exist related to previously mentioned [here](https://github.com/Elijas/auto-youtube-subscription-playlist-2/issues/17#issuecomment-531605757). In fact, all of the sample ids are invalid except for 1veritasium and 2veritasium. I was able to use the script to pull a video from 2veritasium to a playlist I've created, showing that the script does still work.

**Comment by dudemario** [comment]
I'm actually still using your script on a daily basis, and since you haven't changed anything, the script is working. I'll know if it does stop working 😄.

**Comment by Elijas** [comment]
@dudemario Okay, thanks! 

I'm not using the script anymore, so I'm relying on you guys to report status (I had received an email recently).

Let me know if there's a system-wide error so I could focus community efforts:)
