### ISSUE TITLE
Script not adding new videos

### ISSUE THREAD

**Issue by aaronkru** [Elijas/auto-youtube-subscription-playlist-2#41]
The script was working perfectly until yesterday. It doesn't show any errors but new videos are not being added to my playlist. I tried to disable and re-enable the YouTube API but that didn't help. I attached the updatePlaylists script.. could someone please check to see if it looks correct? I have around 1100 videos on my playlist but that shouldn't be an issue (I know it stops working once you have 5000 videos on the playlist).

Heres a screenshot of my sheet: https://www.dropbox.com/s/qlggswdzce5671y/Screenshot%202019-09-18%2010.36.43.png?dl=0

Any help would be appreciated. 
Thanks in advance,

Aaron

[update_playlist.zip](https://github.com/Elijas/auto-youtube-subscription-playlist-2/files/3628152/update_playlist.zip)

**Comment by Elijas** [comment]
@dudemario Could you take a look at this?

**Comment by dudemario** [comment]
Looking into it right now, I can pull and add videos that were created yesterday and before, for some reason the ones created today aren't searchable using YouTube's api

**Comment by dudemario** [comment]
Once again, YouTube has broken its search [as mentioned here](https://stackoverflow.com/a/57982276). We'll just have to wait for them to fix it, nothing we can do.

**Comment by aaronkru** [comment]
@dudemario does the fix you referenced solve the search API issue?

**Comment by dudemario** [comment]
@aaronkru No, that's a separate fix, mainly for error checking. This one is up to YT to fix and they still haven't done it yet.

**Comment by dudemario** [comment]
Does the script add any videos anymore?

**Comment by Fabian42** [comment]
The script has started working again for me. Does anyone else still have problems?

**Comment by dudemario** [comment]
The script works, but sometimes doesn't add videos due to YouTube's Search API missing results. When I run the script, it misses 7 videos and when I [look any of them up on YouTube's Search API](https://developers.google.com/youtube/v3/docs/search/list?apix_params=%7B%22part%22%3A%22snippet%22%2C%22channelId%22%3A%22UCn5GD7VNInaMpYDNfMb4xHQ%22%2C%22publishedAfter%22%3A%222019-09-30T04%3A09%3A17.000Z%22%7D) I can't find [the video I'm looking for](https://www.youtube.com/watch?v=hXu6Y6agMDI). Try running the script yourself and see if you have any missing videos.

**Comment by aaronkru** [comment]
The script seems to be working again for me! I have it set to update every 6 hours. I will keep checking over the next 24 hours to see if misses any videos. I'll report back

**Comment by JesperDramsch** [comment]
Started working again for me.

@dudemario Considering that Youtube at that scale has to use sharding, I can imagine that it might be a "sync issue" on Youtube's side. What I've done to combat that in my script is offset "publishedAfter" by -1h and added the publishedBefore keyword to set it to now() -1. That way I don't get all of the super latest stuff immediately, but at least I (hopefully) get all of them. If it works out, I'll let you know.

**Comment by dudemario** [comment]
Thing is that it's older stuff like 10+ hours before. Anyways, it seems like it's improving, today I was able to run with only 1 missing, so I guess YT is fixing it. @JesperDramsch you should be fine with keeping it as normal since this issue is resolving itself, but if you prefer it that way, go ahead. If no one has any further issues, I'll close this issue in a few days due to not applicable anymore/inactivity.

**Comment by dudemario** [comment]
Thanks for all of your constant monitoring of the script's status, cleared up the issue a lot faster.

**Comment by aaronkru** [comment]
I've been monitoring the script for the past week.. everything seems working again.. Thanks @dudemario and @Elijas for helping with this!
