### ISSUE TITLE
Hitting Daily Quota limit after first execution

### ISSUE THREAD

**Issue by SidGauVic** [Elijas/auto-youtube-subscription-playlist-2#60]
Upon first execution of the Updateplaylist function (after the timestamp is settled) videos will add. However, any attempt to update the sheet afterwards results in the following error: "API call to youtube.playlistItems.insert failed with error: Daily Limit Exceeded."

I've tried to access the quota and view the project, but every time I follow the link it says "failed to load". Is there something I'm missing in the setup to allow me to access the project? Should I try to manually setup the spreadsheet and script vs copying the sheet to see if that resolves the issues?

**Comment by victorjzsun** [comment]
The link they provide is a bit weird. From the sheet, can you go to Tools -> Script Editor -> Resources -> Cloud Platform Project... and tell me what it says under Cloud Platform Project? It will most likely say `This script has an Apps Script–managed Cloud Platform project`. If so, you'll most likely need to create a new Google Cloud Platform project and make the script point there, in order to check quotas there. I'll figure out the steps to do so in the meantime.

**Comment by victorjzsun** [comment]
I have just made a change to the code, which reduces the quota usage. Please make a copy of the sheet again, follow the setup instructions again, and let me know if it works.

**Comment by victorjzsun** [comment]
Closing due to outdated
