### ISSUE TITLE
Update frequency and "findnextrow" clash

### ISSUE THREAD

**Issue by JesperDramsch** [Elijas/auto-youtube-subscription-playlist-2#73]
Using `findnextrow` to set the minimum row in the spreadsheet will skip processing for all preceding rows. If the update frequency of the lower rows is lower than earlier rows, this leads earlier rows to be skipped.

What is the reason to use `findnextrow` instead of simply setting initial `iRow` to `reservedTableRows` to process all rows reliably?

**Comment by victorjzsun** [comment]
I added `findnextrow` for 2 use cases:
1. You have lots of rows in the sheet, and it just so happens that checking all channels leads to a script timeout, leaving later rows to not be checked. By using `findnextrow`, the script can pick up where it left off and continue executing, assuming you run the script enough times.
2. You introduce a new row to the script and want to load close to 200 videos from this row. If you try to run the script, it might pick up videos from rows executed first, and then hit the API quota.

By introducing update frequency, these cases should be covered:
1. Use update frequency to spread rows across multiple calls
2. Assuming the script is running every hour, and no frequency is less than one hour, if you add a row and run the script, that row should be the only one updating, since all others are in cooldown.

Thus, I guess it does make sense to remove `findnextrow`.

**Comment by JesperDramsch** [comment]
I can do that when we finished work on the recursive PR in #72
