### ISSUE TITLE
Quota Exceeded 

### ISSUE THREAD

**Issue by MrCaspan** [Elijas/auto-youtube-subscription-playlist-2#78]
Does this project use the same key and ID? I keep getting 

Could not get subscribed channels, ERROR: Message: [API call to youtube.subscriptions.list failed with error: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.] Details: {"errors":[{"domain":"youtube.quota","message":"The request cannot be completed because you have exceeded your <a href=\"/youtube/v3/getting-started#quota\">quota</a>.","reason":"quotaExceeded"}],"code":403,"message":"The request cannot be completed because you have exceeded your <a href=\"/youtube/v3/getting-started#quota\">quota</a>."}

No matter what day or anything. How do i fix this issues as it was working perfectly fine till about May 22nd and this started to happen. I have thousands of calls i can use but i am curious if this is using your Key and your KEY is reached its limit.

**Comment by victorjzsun** [comment]
I know for sure you aren't using the same key and ID since each script's project (and hence quota) is linked to the spreadsheet it's used in.

If you want to make sure, follow the steps [here](https://developers.google.com/apps-script/guides/cloud-platform-projects#switching_to_a_different_standard_gcp_project) to create a new GCP project and link the script there. Then, assuming you set up everything correctly, you can run your script using that new project and you can view the quota usage on the project's API quotas page.

Make sure you are using the most up to date version, especially if you are using a version that doesn't have the `getVideoIdsWithLessQueries` function.

**Comment by MrCaspan** [comment]
Whats funny is when I go into the section where I select the project to associate the script to it was not associated to any project. How is that possible? Its associated to a dedicated project now and works perfectly fine!

**Comment by victorjzsun** [comment]
Usually when a script is created, it's associated with a default apps script project, as shown below. If it didn't even have this project, then I'm not sure how it even worked!?
![image](https://user-images.githubusercontent.com/17478849/85933135-98249080-b8a1-11ea-9f40-40d37fe545f6.png)

Anyways, glad it works now, you can close this issue if there are no other concerns.

**Comment by MrCaspan** [comment]
Thanks
