### ISSUE TITLE
No videos added to playlists

### ISSUE THREAD

**Issue by Fabian42** [Elijas/auto-youtube-subscription-playlist-2#80]
For a few days already, no new videos get added to my playlists. There's no error message and the debug sheet just says "Acquired 0 videos" for each.

**Comment by Fabian42** [comment]
And just to disagree with me, it just added two videos. But many older ones are still missing.

**Comment by victorjzsun** [comment]
It worked for me these past few days... Try replacing `getVideoIdsWithLessQueries` with `getVideoIds` on [line 121](https://github.com/Elijas/auto-youtube-subscription-playlist-2/blob/master/sheetScript.gs#L121) and change `false` to `true` to set the debug flag on [line 16](https://github.com/Elijas/auto-youtube-subscription-playlist-2/blob/master/sheetScript.gs#L16)

**Comment by Fabian42** [comment]
I have `getVideoIdsWithLessQueries` on line 149 instead. That means I have an outdated version, right? That might partially explain the issue.
I've just copied the 'sheetScript.gs` file into 'Code.gs` in the script editor, that should be enough for an update, right? I'll see how it behaves from now on.

**Comment by victorjzsun** [comment]
Sorry for the late reply, but no! `getVideoIdsWithLessQueries` is the updated version since it uses less of your API quota, while `getVideoIds` is the outdated one. I'm only suggesting you change it for debugging purposes because the request flow is simpler if we want to dive into debugging. If everything works with the current script, awesome. If you want to dive deeper into why it was behaving like that, we can debug further.

**Comment by victorjzsun** [comment]
@Fabian42 If there aren't any updates, I'll close the issue

**Comment by Fabian42** [comment]
I'm still occasionally running different tests, but so far I have not managed to reproduce it while also seeing the log output.

**Comment by Fabian42** [comment]
Got one! "Playlist with id PLbqkLu2V1bJJUQ2aLZjFdz8decGs1kHg- has no new videos", but that was wrong. In the same run, a video from VSauce 2 and one from SpaceX were correctly added to my playlist. Is there anything else that I can check now?

**Comment by victorjzsun** [comment]
I forgot to mention that the sheet's structure changed with the recent updates as well, make sure your sheet looks like this:

![image](https://user-images.githubusercontent.com/17478849/95020877-c9002880-063b-11eb-9045-0d36b16d807c.png)

I ran the last line with the playlist you gave and an appropriate timestamp and it seems to work for me. I'm not too sure what's wrong, maybe try isolating that one cell so that you only update with videos from that playlist and see if that works?

**Comment by victorjzsun** [comment]
@Fabian42 any update on this?

**Comment by Fabian42** [comment]
I haven't really noticed anything recently, but I've also not checked all channels manually anymore. I guess this can be closed for now and reopened if someone observes it again.
