### ISSUE TITLE
Cryptic Column Titles

### ISSUE THREAD

**Issue by AceFrahm** [Elijas/auto-youtube-subscription-playlist-2#91]
I can't figure out what each column on the google spreadsheet truly means.  Can you please explain them in the instructions?

"Last Update (Timestamp)"
"Frequency (hours)"
"Delete (days)"
"<--"

I kind get what Delete is for, but exactly what it does when to which items is not clear at all.
I have no idea what "Frequency" does, I think I have to run the functions by hand right?  This thing doesn't run the update function by itself on a timer, does it?

**Comment by victorjzsun** [comment]
Yeah, I'll update the readme. For the time being, here's the description. When the script is run, all videos published after the datetime specified in Last Update column is added to the playlist. If this column is blank, the default is one day before current time so all videos published in the last 24 hours will be added to the playlist. If Frequency column is filled in, it also checks if the time between Last Update time and current time is at least <Frequency> hours. If it is, the script runs for that row, otherwise, it skips that row. Frequency column is usually used if different rows should be updated at different intervals. If the Delete column is filled in, all videos in the playlist that are <Delete> days old are automatically deleted from the playlist. <-- does not represent anything.

For running the script automatically, follow the steps outlined in https://github.com/Elijas/auto-youtube-subscription-playlist-2#scheduled-playlist-update. You don't need Frequency column for a simple timed trigger, it's only used for checking different rows at different intervals

**Comment by AceFrahm** [comment]
Thank you, your response was so fast and I now have mine running once every hour!
