### ISSUE TITLE
Channel vs. user ID ambiguity

### ISSUE THREAD

**Issue by Fabian42** [Elijas/auto-youtube-subscription-playlist-2#98]
I wanted to add https://www.youtube.com/c/skate702 to my script, so I wrote "skate702" into a cell. Instead, it seems to use "https://www.youtube.com/user/SkAtE702". I have now inserted "UCgSJ92_7N3_TOHvKxN2yV1w" instead and will see how that goes.  
Is there something that the script can do against such ambiguities? Also, often channel names don't work at all, is that the same issue and why does that happen?

**Comment by victorjzsun** [comment]
Custom URLs are not supported at all and usernames (yt.com/user/...) are somewhat supported, all due to the YouTube Data API, nothing we can do on our end. One solution for finding by custom URL is described in [this SO post](https://stackoverflow.com/posts/37947865/revisions), but it's not perfect either. The best way is to use channel IDs for everything, I updated the readme to be a bit clearer.

**Comment by victorjzsun** [comment]
Possible temporary solutions proposed in https://github.com/Elijas/auto-youtube-subscription-playlist-2/issues/83, closing this one as a duplicate and continue discussion there
