### ISSUE TITLE
"Exception: The number of rows in the range must be at least 1." error in latest release

### ISSUE THREAD

**Issue by KnifeFed** [Elijas/auto-youtube-subscription-playlist-2#99]
Hiya!

I just switched to the latest version of the script and when I run the function I get this error message:

`Exception: The number of rows in the range must be at least 1.`

There is no output in the Debug sheet.

Do I need to start over with a fresh copy of the Sheet?

**Comment by victorjzsun** [comment]
If you are using an old version of the spreadsheet, you'll want to make a copy of the new spreadsheet as described in [Set-Up Instructions](https://github.com/Elijas/auto-youtube-subscription-playlist-2#set-up-instructions) since the format of the spreadsheet has changed. Either load your data/triggers into the new spreadsheet or copy the sheets to your old spreadsheet. If you are copying sheets across spreadsheets, make sure to use the [built-in functionality](https://help.tillerhq.com/en/articles/2844735-how-to-copy-a-sheet-tab-to-another-google-sheet) rather than copy-paste because the dropdown menu will not be copied

**Comment by KnifeFed** [comment]
I guess I skimmed because now I see that was even mentioned in the release notes 🤦‍♂️

Thank you!
